apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: udev-display
spec:
  brokerProperties: {}
  brokerSpec:
    brokerPodSpec:
      containers:
        - name: x11
          image: registry.opensuse.org/home/atgracey/wallboardos/15.5/x11test:icewm
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /root
              name: home
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 5
      volumes:
        - name: tmp
          emptyDir: {}
        - name: home
          emptyDir: {}
  capacity: 1
  discoveryHandler:
    name: display
