apiVersion: apps/v1
kind: Deployment
metadata:
  name: x11icewm
  namespace: x11-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      ui: x11test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      namespace: x11-ui
      labels:
        ui: x11test
    spec:
      containers:
        - image: registry.opensuse.org/home/atgracey/wallboardos/15.5/x11test:icewm
          imagePullPolicy: Always
          name: x11-icewm
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /tmp
            type: ''
          name: tmp
        - hostPath:
            path: /root
            type: ''
          name: home