apiVersion: v1
kind: Namespace
metadata:
  name: x11-ui
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: browser-config
  namespace: x11-ui
data:
  url: https://build.opensuse.org
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser
  namespace: x11-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      ui: x11test
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: x11-ui
      labels:
        ui: x11test
    spec:
      containers:
        - name: wallboard   
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: browser-config
                  key: url
            - name: DISPLAY
              value: ':0'
          image: registry.opensuse.org/home/atgracey/wallboardos/15.5/firefox:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            privileged: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /home/user/
              name: home
            - mountPath: /root/
              name: home
            - mountPath: /dev
              name: devices
        - name: x11
          image: registry.opensuse.org/home/atgracey/wallboardos/15.5/x11:icewm
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /root
              name: home
            - mountPath: /dev
              name: devices
      initContainers:
        - name: clear-tmp
          image: busybox:1.28
          command: ['sh', '-c', "rm -r /tmp/.X11-unix; rm /home/user/.Xauthority"]
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /home/user
              name: home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /tmp
            type: ''
          name: tmp
        - hostPath:
            path: /root
            type: ''
          name: home
        - hostPath:
            path: /dev
            type: ''
          name: devices